name = "AbstractItemResponseModels"
uuid = "0ab3451c-659c-47cd-a7a9-a2d579e209dd"
authors = ["Philipp Gewessler"]
version = "0.1.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
StatsBase = "0.33"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
